// <auto-generated />
namespace GestionContacts2.WebUi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class SuppressionNavigationUserDansContact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SuppressionNavigationUserDansContact));
        
        string IMigrationMetadata.Id
        {
            get { return "202508240411078_SuppressionNavigationUserDansContact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
